model:
  name: linoss
  hidden_dim: 128
  encoder:
    target: LinearEncoder
    kwargs:
      use_bias: false
  backbone:
    target: LinOSS
    kwargs:
      num_blocks: 4
      state_dim: 128
      num_heads: 1
      use_head_gating: false
      use_head_output_projection: false
      drop_rate: 0.1
      prenorm: true
      discretization: IMEX
      initialization: AG
      damping: true
      stability: stable
      A_max: 1.0
      G_max: 0.2
  head:
    target: ClassificationHead
    kwargs:
      reduce: true
